# Generated by Django 3.2.9 on 2021-12-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='free',
        ),
    ]
